version: '3.3'

volumes:
  db_data:

services:
  db:
    image: 'postgres:latest'
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - '.db.env'
    ports:
      - '5432:5432'

  rabbit:
    image: 'rabbitmq:latest'
    ports:
      - '5672:5672'
      - '15672:15672'