version: '3.3'

volumes:
  db_data:

services:
  db:
    image: 'postgres:14.4-alpine'
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - '.db.env'
    ports:
      - '5433:5432'