server:
  port: 8082

spring:
  application:
    name: resource-service

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}

  cloud:
    stream:
      function:
        bindings:
          input-in-0: binary-processing-input

      bindings:
        binary-processing-input:
          destination: binary-processing
          group: main
          consumer:
            max-attempts: 3
            auto-bind-dlq: true

resilience4j:
  retry:
    instances:
      rest-retry:
        maxRetryAttempts: 5

  circuitbreaker:
    instances:
      rest-circuit-breaker:
        failureRateThreshold: 75
        slidingWindowType: TIME_BASED
        slidingWindowSize: 30
        automaticTransitionFromOpenToHalfOpenEnabled: true



service-gateway:
  url: ${SERVICE_GATEWAY_URL:http://localhost:8090}