server:
  port: 8082

spring:
  application:
    name: resource-service

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}

  cloud:
    stream:
      function:
        bindings:
          input-in-0: binary-processing-input

      bindings:
        binary-processing-input:
          destination: binary-processing
          group: main
          consumer:
            max-attempts: 3
            auto-bind-dlq: true

resilience4j:
  retry:
    instances:
      save-metadata:
        maxRetryAttempts: 5
      download-file:
        maxRetryAttempts: 5

resource-service:
  url: ${RESOURCE_SERVICE_URL:http://localhost:8080}

song-service:
  url: ${SONG_SERVICE_URL:http://localhost:8081}