version: '3.3'

volumes:
  resource-db-data:
  song-db-data:
  storage-db-data:
  elasticsearch-data:

services:
  resource-service:
    image: resource-service:latest
    build: ../resource-service
    env_file:
      - ${ENV_FILE}
    depends_on:
      - resource-db
      - localstack
      - rabbit
      - service-registry

  song-service:
    image: song-service:latest
    build: ../song-service
    env_file:
      - ${ENV_FILE}
    depends_on:
      - song-db
      - service-registry

  resource-processor:
    image: resource-processor:latest
    build: ../resource-processor
    env_file:
      - ${ENV_FILE}
    depends_on:
      - rabbit
      - service-gateway

  storage-service:
    image: storage-service:latest
    build: ../storage-service
    env_file:
      - ${ENV_FILE}
    depends_on:
      - storage-db
      - service-gateway
      
  resource-db:
    image: postgres:14.4-alpine
    volumes:
      - resource-db-data:/var/lib/postgresql/data
    env_file:
      - ${ENV_FILE}
    environment:
      - POSTGRES_DB=${RESOURCE_DB_NAME}
      - POSTGRES_USER=${RESOURCE_DB_USERNAME}
      - POSTGRES_PASSWORD=${RESOURCE_DB_PASSWORD} 

  song-db:
    image: postgres:14.4-alpine
    volumes:
      - song-db-data:/var/lib/postgresql/data
    env_file:
      - ${ENV_FILE}
    environment:
      - POSTGRES_DB=${SONG_DB_NAME}
      - POSTGRES_USER=${SONG_DB_USERNAME}
      - POSTGRES_PASSWORD=${SONG_DB_PASSWORD} 

  storage-db:
    image: postgres:14.4-alpine
    volumes:
      - storage-db-data:/var/lib/postgresql/data
    env_file:
      - ${ENV_FILE}
    environment:
      - POSTGRES_DB=${STORAGE_DB_NAME}
      - POSTGRES_USER=${STORAGE_DB_USERNAME}
      - POSTGRES_PASSWORD=${STORAGE_DB_PASSWORD} 

  localstack:
    image: 'localstack/localstack:latest'

  rabbit:
    image: rabbitmq:3.10.6-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  service-registry:
    image: service-registry:latest
    build: ../service-registry
    ports:
      - 8761:8761

  service-gateway:
    image: service-gateway:latest
    build: ../service-gateway
    env_file:
      - ${ENV_FILE}
    ports:
      - 8090:8090
    depends_on:
      - service-registry

  elasticsearch:
    image: elasticsearch:8.3.3
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - XPACK_SECURITY_ENABLED=false
      - xpack.security.enabled=false

  logstash:
    image: logstash:8.3.3
    ports:
      - 5046:5046
    volumes:
      - ./logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./logstash/pipelines/rabbit.conf:/usr/share/logstash/config/pipelines/rabbit.conf


  kibana:
    image: kibana:8.3.3
    ports:
      - 5601:5601
    env_file:
      - ${ENV_FILE}
    depends_on:
      - elasticsearch