version: '3.3'

volumes:
  resource-db-data:
  song-db-data:

services:
  resource-service:
    image: resource-service:latest
    build: ../resource-service
    ports:
      - 8080:8080
    env_file:
      - ${ENV_FILE}
    depends_on:
      - resource-db
      - localstack
      - rabbit

  song-service:
    image: song-service:latest
    build: ../song-service
    ports:
      - 8081:8081
    env_file:
      - ${ENV_FILE}
    depends_on:
      - song-db
      - rabbit

  resource-processor:
    image: resource-processor:latest
    build: ../resource-processor
    ports:
      - 8082:8082
    env_file:
      - ${ENV_FILE}
    depends_on:
      - rabbit
      - resource-service
      - song-service
      
  resource-db:
    image: postgres:14.4-alpine
    volumes:
      - resource-db-data:/var/lib/postgresql/data
    env_file:
      - ${ENV_FILE}
    environment:
      - POSTGRES_DB=${RESOURCE_DB_NAME}
      - POSTGRES_USER=${RESOURCE_DB_USERNAME}
      - POSTGRES_PASSWORD=${RESOURCE_DB_PASSWORD} 
    ports:
      - 5432:5432

  song-db:
    image: postgres:14.4-alpine
    volumes:
      - song-db-data:/var/lib/postgresql/data
    env_file:
      - ${ENV_FILE}
    environment:
      - POSTGRES_DB=${SONG_DB_NAME}
      - POSTGRES_USER=${SONG_DB_USERNAME}
      - POSTGRES_PASSWORD=${SONG_DB_PASSWORD} 
    ports:
      - 5433:5432

  localstack:
    image: 'localstack/localstack:latest'
    ports:
      - '4566:4566'

  rabbit:
    image: rabbitmq:3.10.6-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
  