spring:
  application:
    name: song-service

  datasource:
    url: jdbc:postgresql://${SONG_DB_HOST:localhost}:${SONG_DB_PORT:5433}/${SONG_DB_NAME:metadata}
    username: ${SONG_DB_USERNAME:postgres}
    password: ${SONG_DB_PASSWORD:postgres}
  jpa:
    generate-ddl: true

service:
  csv:
    max-length: 5

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}