server:
  port: 8085

spring:
  application:
    name: storage-service

  datasource:
    url: jdbc:postgresql://${STORAGE_DB_HOST:localhost}:${STORAGE_DB_PORT:5432}/${STORAGE_DB_NAME:storage}
    username: ${STORAGE_DB_USERNAME:postgres}
    password: ${STORAGE_DB_PASSWORD:postgres}

  jpa:
    generate-ddl: true

  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}

  cloud:
    stream:
      bindings:
        logs-output:
          destination: logs
          group: main
          producer:
            required-groups: main

service:
  csv:
    max-length: 199
  messaging:
    logs-binding: logs-output

  auth:
    client-id: ${GITHUB_CLIENT_ID}
    client-secret: ${GITHUB_CLIENT_SECRET}
    redirect-uri: ${GITHUB_REDIRECT_URI}
    auth-uri: https://github.com/login/oauth/authorize?response_type=code&client_id=${service.auth.client-id}&scope=read:user&redirect_uri=${service.auth.redirect-uri}

    jwt:
      secret-key: ${JWT_SECRET_KEY}
      validity-time: 1


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}