spring:
  application:
    name: resource-service

  datasource:
    url: jdbc:postgresql://localhost:5432/binary
    username: postgres
    password: postgres

  jpa:
    generate-ddl: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    stream:
      bindings:
        binary-processing-output:
          destination: binary-processing
          group: main
          producer:
            required-groups: main

aws:
  region: us-east-1
  configuration:
    endpoint:
      enabled: true
      url: http://localhost.localstack.cloud:4566
  s3:
    bucket:
      name: binary

service:
  csv:
    max-length: 199
  messaging:
    binary-processing-binding: binary-processing-output