spring:
  application:
    name: resource-service

  datasource:
    url: jdbc:postgresql://${RESOURCE_DB_HOST:localhost}:${RESOURCE_DB_PORT:5432}/${RESOURCE_DB_NAME:binary}
    username: ${RESOURCE_DB_USERNAME:postgres}
    password: ${RESOURCE_DB_PASSWORD:postgres}

  jpa:
    generate-ddl: true

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}

  cloud:
    stream:
      bindings:
        binary-processing-output:
          destination: binary-processing
          group: main
          producer:
            required-groups: main

aws:
  region: us-east-1
  configuration:
    endpoint:
      enabled: true
      url: ${AWS_CONFIGURATION_ENDPOINT_URL:http://localhost.localstack.cloud:4566}
  s3:
    bucket:
      name: binary

service:
  csv:
    max-length: 199
  messaging:
    binary-processing-binding: binary-processing-output

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}